Update community.yml
EddieJaoudeCommunity/EddieBotUI pull request #44
Opened 2021-02-25 18:20 UTC by muthuannamalai12

I have updated the issue-message, Pr-Message with new ones, and added a footer in Community.yml

2021-02-27 22:39 UTC, BOLT04 reviewed
Thank you for your contribution @muthuannamalai12 👍, but what do you think about making this PR on the `template` repo? The [file on that repo](https://github.com/EddieHubCommunity/template/blob/main/.github/workflows/community.yml) should be used in all others I believe.

It's easier to keep all workflows consistent if we start using them from the `template` repo.
Let me know what you think 😃.

2021-03-04 06:14 UTC, Vyvy-vi requested changes

2021-03-04 06:14 UTC, Vyvy-vi commented on .github/workflows/community.yml
> +          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Dis
Could we use the verbiage- Discord Server and but the hyperlink on Discord Server for consistency?
```suggestion
          footer: 'If you would like to continue contributing to open source and would like to do it with an awesome inclusive community, you should join our <a href="http://discord.eddiehub.org">Discord Server</a> and our <a href="http://github.eddiehub.org">GitHub Organisation</a> - we help and encourage each other to contribute to open source little and often 🤓 . Any questions let us know.'
```

2021-03-14 22:11 UTC, Vyvy-vi approved these changes
LGTM-!

2021-03-15 10:00 UTC, galahad42 approved these changes

2021-03-20 21:38 UTC, eddiejaoude commented
Thanks everyone 👍

2021-03-20 21:40 UTC, eddiejaoude approved these changes
Great work everyone 👍

2021-03-20 21:41 UTC, merged