Added an permanent discord invite link
EddieJaoudeCommunity/EddieBotUI pull request #50
Opened 2021-09-15 08:09 UTC by rahul-mishra-oops

2021-09-18 21:50 UTC, BOLT04 reviewed
Hi @rahul-mishra-oops, thank you for your contribution 👍. Just left a comment to make the link and community name consistent with other repos 🙂

2021-09-18 21:50 UTC, BOLT04 commented on README.md
> +EddieBotUI is a web application built to display all kinds of information about the **Eddie Jaoude Discord community** - [click to join](https://discord.gg/dCUbX7tYUf) - like users biography, usage s
This should be updated to be consistent with other repos, how about this:
```suggestion
EddieBotUI is a web application built to display all kinds of information about the **EddieHub Discord community** - [click to join](http://discord.eddiehub.org) - like users biography, usage stats, badges and more.
```

2021-11-21 05:41 UTC, krishguptadev requested changes
Please see the comments left above.

2021-11-21 05:42 UTC, krishguptadev requested changes
Duplicate of #49

2021-12-09 23:52 UTC, eddiejaoude commented
Thank you for the contribution. I am going to close it has been fixed

2021-12-09 23:52 UTC, closed without merging